# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`


In [2]:
a = np.zeros(10)

In [3]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [4]:
a = np.zeros(10)

a[4] = 1

a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [5]:
b = np.arange(10, 49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [6]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [7]:
a = np.array([1,2,0,0,4,0])

a[np.nonzero(a)]

array([1, 2, 4])

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`


In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`


In [9]:
a = np.random.random((3,3))
a

array([[0.01940931, 0.70358214, 0.75714009],
       [0.86886006, 0.51297705, 0.0474661 ],
       [0.65500871, 0.21546116, 0.98462463]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [10]:
a = np.random.random ((10,10))

a

np.min(a)
np.max(a)

0.9892053590841718

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [11]:
a = np.random.random((6,5))

a

np.mean(a)

0.4758323590187253

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [31]:
a = np.random.random((5,5))
                     
a

np.diag(a,k=-1)

a[np.diag(a,k=-1)] = ([1,2,3,4])

IndexError: arrays used as indices must be of integer (or boolean) type

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [16]:
b = np.random.random((5,5))

b

db = (b-np.mean(b))/np.std(b)

db

array([[ 0.67411675,  1.63884626, -0.06256019, -0.29721317, -1.26998179],
       [-0.87950901, -1.33906441, -0.5611702 , -0.16419199,  0.55178108],
       [ 1.1744776 ,  1.41859754, -0.35495137, -0.77578045,  0.61637593],
       [-1.35525872, -1.61236377, -1.08717132,  0.05870511,  1.4681255 ],
       [-0.33257394, -0.46785332,  1.71023366,  0.06237563,  1.18600855]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [17]:
x1 = np.random.random(10)
x2 = np.random.random(10)

np.intersect1d(x1,x2)


array([], dtype=float64)

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [18]:
x = np.random.random(10)

x

np.sort(x)

array([0.03153986, 0.12386325, 0.26124173, 0.29840285, 0.44700827,
       0.54745061, 0.65847933, 0.73618817, 0.78000626, 0.95099565])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [21]:
c = np.random.random(10)

np.argmax(c)

c[np.argmax(c)] = 0

c

array([0.61359033, 0.        , 0.43398296, 0.9340068 , 0.98374172,
       0.42463686, 0.84632884, 0.01687323, 0.72479273, 0.23238491])

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [62]:
n = np.random.random((3,3))

np.mean(n, axis=1)

m = n - np.mean(n, axis=1)

m

array([[-0.2093802 ,  0.34984984,  0.05933969],
       [-0.10724597, -0.09634678, -0.16915408],
       [-0.18034362,  0.33578808,  0.01749305]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`
