# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [23]:
import numpy as np
import random

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`


In [24]:
a = np.zeros(10)

In [25]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [26]:
a = np.zeros(10)

a[4] = 1

a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [27]:
b = np.arange(10, 49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [28]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [29]:
a = np.array([1,2,0,0,4,0])

a[np.nonzero(a)]

array([1, 2, 4])

In [30]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`


In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`


In [32]:


a = np.random.random((3,3))
a

array([[0.75997277, 0.81541888, 0.54362743],
       [0.90875887, 0.47620786, 0.2151512 ],
       [0.09297254, 0.91310146, 0.23327552]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [45]:
a = np.random.randint(-100,100,(10,10))

np.min(a)
np.max(a)

96

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [11]:
a = np.random.random((6,5))

a

np.mean(a)

0.4758323590187253

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [16]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [34]:
b = np.random.random((5,5))

b

db = (b-np.mean(b))/np.std(b)

db

array([[-1.06214721,  0.83077562,  1.46027114,  0.5227985 ,  1.27497829],
       [-0.60060821, -0.96312834,  0.1824476 ,  1.6521781 , -1.08586599],
       [ 0.25078139, -0.55543953,  0.70498999,  1.15426167,  0.40515345],
       [ 0.4253055 ,  1.57450348, -1.44127469, -0.16262784, -0.04200084],
       [-1.54833262, -1.2667784 ,  0.35790611, -0.52375267, -1.54439447]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [17]:
x1 = np.random.random(10)
x2 = np.random.random(10)

np.intersect1d(x1,x2)


array([], dtype=float64)

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [18]:
x = np.random.random(10)

x

np.sort(x)

array([0.03153986, 0.12386325, 0.26124173, 0.29840285, 0.44700827,
       0.54745061, 0.65847933, 0.73618817, 0.78000626, 0.95099565])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [49]:
c = np.random.random(10)

np.argmax(c)

c[np.argmax(c)] = 0

c

array([0.26918912, 0.28137176, 0.17715067, 0.61536757, 0.69632745,
       0.19707437, 0.65477417, 0.49382254, 0.        , 0.29510633])

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [57]:
n = np.random.random((3,3))

n

m = n - np.mean(n, axis=1, keepdims=True)

m

array([[-0.06657941, -0.15999078,  0.22657019],
       [ 0.10254606, -0.12675179,  0.02420573],
       [ 0.13916329,  0.06901169, -0.20817498]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [62]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print(np.argpartition.__doc__)


    Perform an indirect partition along the given axis using the
    algorithm specified by the `kind` keyword. It returns an array of
    indices of the same shape as `a` that index data along the given
    axis in partitioned order.

    .. versionadded:: 1.8.0

    Parameters
    ----------
    a : array_like
        Array to sort.
    kth : int or sequence of ints
        Element index to partition by. The k-th element will be in its
        final sorted position and all smaller elements will be moved
        before it and all larger elements behind it. The order all
        elements in the partitions is undefined. If provided with a
        sequence of k-th it will partition all of them into their sorted
        position at once.
    axis : int or None, optional
        Axis along which to sort. The default is -1 (the last axis). If
        None, the flattened array is used.
    kind : {'introselect'}, optional
        Selection algorithm. Default is 'introselect'
    order : str

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [63]:
l = np.random.randint(0,10,size=(5,3))

In [64]:
l

array([[2, 1, 5],
       [9, 4, 7],
       [0, 3, 6],
       [8, 2, 5],
       [3, 4, 1]])

In [65]:
l = np.where(l>4)

In [72]:
l [np.where(l>4)] = l([i])

NameError: name 'i' is not defined